// Generated by CoffeeScript 1.3.3
﻿;

var BASE_API_PATH, console, router;

console = console || {};

console.log = console.log || function() {
  return null;
};

_.extend(_.templateSettings, {
  interpolate: /\{\{(.+?)\}\}/g
});

BASE_API_PATH = "/";

require.config({
  paths: {
    "scripts": "../..",
    "templates": "../../templates"
  },
  urlArgs: "bust=" + (new Date()).getTime()
});

router = null;

$(function() {
  BASE_API_PATH = $("#base_path").val();
  return define(['ISWPRouter'], function(ISWPRouter) {
    router = new ISWPRouter();
    return Backbone.history.start();
  });
});
