// Generated by CoffeeScript 1.3.3
﻿;

var BASE_API_PATH, console;

console = console || {};

console.log = console.log || function() {
  return null;
};

_.extend(_.templateSettings, {
  interpolate: /\{\{(.+?)\}\}/g
});

BASE_API_PATH = "/";

require.config({
  paths: {
    "scripts": "../..",
    "templates": "../../templates"
  },
  urlArgs: "bust=" + (new Date()).getTime()
});

$(function() {
  BASE_API_PATH = $("#base_path").val();
  return define(['ISWPWorkspace'], function(ISWPWorkspace) {
    this.workspace = new ISWPWorkspace();
    return Backbone.history.start();
  });
});
