// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/AppView'], function(AppView) {
  var ISWPWorkspace;
  return ISWPWorkspace = (function(_super) {

    __extends(ISWPWorkspace, _super);

    function ISWPWorkspace() {
      return ISWPWorkspace.__super__.constructor.apply(this, arguments);
    }

    ISWPWorkspace.prototype.initialize = function(options) {};

    ISWPWorkspace.prototype.routes = {
      "": "index",
      "wms": "index",
      "wms/region/:regionLetter": "wmsRegion",
      "wms/county/:countyId": "wmsCounty",
      "wms/type/:typeId": "wmsType"
    };

    ISWPWorkspace.prototype.index = function() {
      var appView;
      appView = new AppView({
        el: $('#appContainer')[0]
      });
      appView.render();
    };

    ISWPWorkspace.prototype.wmsRegion = function(regionLetter) {
      console.log(regionLetter);
    };

    ISWPWorkspace.prototype.wmsCounty = function(countyId) {
      console.log(countyId);
    };

    ISWPWorkspace.prototype.wmsType = function(typeId) {
      console.log(typeId);
    };

    return ISWPWorkspace;

  })(Backbone.Router);
});
