// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['namespace', 'views/MapView', 'views/ThemeNavView', 'views/YearNavView', 'views/MapToolsView', 'views/BreadcrumbView', 'views/CountyNetSupplyCollectionView', 'views/RegionStrategyCollectionView', 'views/CountyStrategyCollectionView', 'views/StrategyTypeCollectionView', 'views/EntityStrategyCollectionView', 'views/CountyRegionSelectView', 'collections/StrategyTypeCollection', 'collections/CountyCollection', 'collections/RegionCollection'], function(namespace, MapView, ThemeNavView, YearNavView, MapToolsView, BreadcrumbView, CountyNetSupplyCollectionView, RegionStrategyCollectionView, CountyStrategyCollectionView, StrategyTypeCollectionView, EntityStrategyCollectionView, CountyRegionSelectView, StrategyTypeCollection, CountyCollection, RegionCollection) {
  var ISWPRouter;
  return ISWPRouter = (function(_super) {

    __extends(ISWPRouter, _super);

    function ISWPRouter() {
      return ISWPRouter.__super__.constructor.apply(this, arguments);
    }

    ISWPRouter.prototype.initialize = function(options) {
      _.bindAll(this, 'updateViewsToNewYear');
      this.currTableView = null;
      this.currYear = "2010";
      this.tableContainer = $('#tableContainer')[0];
      this.mapView = new MapView({
        mapContainerId: 'mapContainer',
        bingApiKey: $('#bing_maps_key').val()
      });
      this.mapView.render();
      this.mapToolsView = new MapToolsView({
        el: $('#mapTools')[0],
        mapView: this.mapView
      });
      this.mapToolsView.render();
      this.themeNavView = new ThemeNavView({
        el: $('#themeNavContainer')[0]
      });
      this.themeNavView.render();
      this.yearNavView = new YearNavView({
        startingYear: this.currYear,
        el: $('#yearNavContainer')[0]
      });
      this.yearNavView.render();
      this.yearNavView.currentYear.subscribe(this.updateViewsToNewYear);
      this.breadcrumbList = new BreadcrumbView({
        el: $('#breadcrumbContainer')[0]
      });
      this.breadcrumbList.render();
      namespace.strategyTypes = new StrategyTypeCollection();
      namespace.strategyTypes.reset(initStrategyTypes);
      namespace.countyNames = new CountyCollection();
      namespace.countyNames.reset(initCountyNames);
      namespace.regionNames = new RegionCollection();
      namespace.regionNames.reset(initRegionNames);
      this.countyRegionSelect = new CountyRegionSelectView({
        el: $('#regionCountySelectContainer')[0],
        counties: namespace.countyNames,
        regions: namespace.regionNames
      });
      this.countyRegionSelect.render();
    };

    ISWPRouter.prototype.updateViewsToNewYear = function(newYear) {
      this.currYear = newYear;
      this.currTableView.changeToYear(newYear);
    };

    ISWPRouter.prototype.routes = {
      "": "wmsNetCountySupplies",
      "wms": "wmsNetCountySupplies",
      "wms/region/:regionLetter": "wmsRegion",
      "wms/county/:countyId": "wmsCounty",
      "wms/type/:typeId": "wmsType",
      "wms/entity/:entityId": "wmsEntity"
    };

    ISWPRouter.prototype.wmsNetCountySupplies = function() {
      if (this.currTableView != null) {
        this.currTableView = this.currTableView.unrender();
      }
      this.currTableView = new CountyNetSupplyCollectionView({
        el: this.tableContainer,
        currYear: this.currYear
      });
      this.currTableView.render();
    };

    ISWPRouter.prototype.wmsRegion = function(regionLetter) {
      if (this.currTableView != null) {
        this.currTableView = this.currTableView.unrender();
      }
      this.currTableView = new RegionStrategyCollectionView({
        el: this.tableContainer,
        currYear: this.currYear,
        id: regionLetter,
        name: regionLetter
      });
      this.currTableView.render();
    };

    ISWPRouter.prototype.wmsCounty = function(countyId) {
      var countyName;
      if (this.currTableView != null) {
        this.currTableView = this.currTableView.unrender();
      }
      countyName = namespace.countyNames.get(countyId).get('name');
      this.currTableView = new CountyStrategyCollectionView({
        el: this.tableContainer,
        currYear: this.currYear,
        id: countyId,
        name: countyName
      });
      this.currTableView.render();
    };

    ISWPRouter.prototype.wmsType = function(typeId) {
      var typeName;
      if (this.currTableView != null) {
        this.currTableView = this.currTableView.unrender();
      }
      typeName = namespace.strategyTypes.get(typeId).get('name');
      this.currTableView = new StrategyTypeCollectionView({
        el: this.tableContainer,
        currYear: this.currYear,
        id: typeId,
        name: typeName
      });
      this.currTableView.render();
    };

    ISWPRouter.prototype.wmsEntity = function(entityId) {
      var EntityModel, entity,
        _this = this;
      if (this.currTableView != null) {
        this.currTableView = this.currTableView.unrender();
      }
      EntityModel = Backbone.Model.extend({
        url: "" + BASE_API_PATH + "api/entity/" + entityId
      });
      entity = new EntityModel();
      entity.fetch({
        success: function(model) {
          console.log(model);
          _this.currTableView = new EntityStrategyCollectionView({
            el: _this.tableContainer,
            currYear: _this.currYear,
            id: entityId,
            name: model.get("name")
          });
          _this.currTableView.render();
        }
      });
    };

    return ISWPRouter;

  })(Backbone.Router);
});
