// Generated by CoffeeScript 1.3.3

define(['WMSRouter'], function(WMSRouter) {
  var initialize;
  initialize = function() {
    var wmsRouter;
    wmsRouter = new WMSRouter();
    Backbone.history.start();
  };
  return {
    initialize: initialize
  };
});
