// Generated by CoffeeScript 1.3.3
var BASE_API_PATH, console;

console = console || {};

console.log = console.log || function() {
  return null;
};

_.extend(_.templateSettings, {
  interpolate: /\{\{(.+?)\}\}/g
});

BASE_API_PATH = "/";

$(function() {
  var _this = this;
  BASE_API_PATH = $("#base_path").val();
  require.config({
    baseUrl: "" + BASE_API_PATH + "Scripts/Compiled/backbone_app",
    paths: {
      "scripts": "../..",
      "templates": "../../templates"
    }
  });
  require(['namespace', 'WMSRouter'], function(namespace, WMSRouter) {
    var MyHistory;
    MyHistory = Backbone.History.extend({
      loadUrl: function() {
        var match;
        match = Backbone.History.prototype.loadUrl.apply(this, arguments);
        if (!match) {
          this.trigger('route-not-found');
        }
        return match;
      }
    });
    Backbone.history = new MyHistory();
    Backbone.history.on("route-not-found", function() {
      Backbone.history.navigate("", {
        trigger: true
      });
    });
    namespace.bootstrapData().done(function() {
      var r;
      r = new WMSRouter();
      Backbone.history.start();
    }).fail(function() {
      alert("An error has occured.  Please reload this page or go back.");
    });
  });
});
