// Generated by CoffeeScript 1.3.3

define(['collections/WugFeatureCollection'], function(WugFeatureCollection) {
  var namespace;
  namespace = {};
  namespace.wugFeatureCollection = new WugFeatureCollection();
  console.log("in namespace");
  return namespace;
});
