// Generated by CoffeeScript 1.3.3

define(['collections/WugFeatureCollection'], function(WugFeatureCollection) {
  var namespace;
  namespace = {};
  namespace.wugFeatureCollection = new WugFeatureCollection();
  namespace.VALID_YEARS = ["2010", "2020", "2030", "2040", "2050", "2060"];
  namespace.currYear = "2010";
  return namespace;
});
