// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['namespace', 'views/MapView', 'views/MapTopToolbarView', 'views/YearNavView', 'views/MapBottomToolbarView', 'views/CountyNetSupplyCollectionView', 'views/RegionStrategyCollectionView', 'views/CountyStrategyCollectionView', 'views/StrategyTypeCollectionView', 'views/EntityStrategyCollectionView', 'views/StrategyDetailCollectionView', 'views/WmsAreaSelectView', 'collections/StrategyTypeCollection', 'collections/CountyCollection', 'collections/RegionCollection', 'collections/HouseCollection', 'collections/SenateCollection'], function(namespace, MapView, MapTopToolbarView, YearNavView, MapBottomToolbarView, CountyNetSupplyCollectionView, RegionStrategyCollectionView, CountyStrategyCollectionView, StrategyTypeCollectionView, EntityStrategyCollectionView, StrategyDetailCollectionView, WmsAreaSelectView, StrategyTypeCollection, CountyCollection, RegionCollection, HouseCollection, SenateCollection) {
  var WMSRouter;
  return WMSRouter = (function(_super) {

    __extends(WMSRouter, _super);

    function WMSRouter() {
      return WMSRouter.__super__.constructor.apply(this, arguments);
    }

    WMSRouter.prototype.initialize = function(options) {
      _.bindAll(this, 'updateViewsToNewYear', 'updateSelectedWug');
      this.currTableView = null;
      this.tableContainer = $('#tableContainer')[0];
      this.mapView = new MapView({
        mapContainerId: 'mapContainer',
        bingApiKey: $('#bing_maps_key').val()
      });
      this.mapView.render();
      this.mapBottomToolbarView = new MapBottomToolbarView({
        el: $('#mapBottomToolsContainer')[0],
        mapView: this.mapView
      });
      this.mapBottomToolbarView.render();
      this.mapTopToolbarView = new MapTopToolbarView({
        el: $('#mapTopToolbarContainer')[0],
        mapView: this.mapView
      });
      this.yearNavView = new YearNavView({
        el: $('#yearNavContainer')[0]
      });
      namespace.strategyTypes = new StrategyTypeCollection();
      namespace.strategyTypes.reset(initStrategyTypes);
      namespace.countyNames = new CountyCollection();
      namespace.countyNames.reset(initCountyNames);
      namespace.regionNames = new RegionCollection();
      namespace.regionNames.reset(initRegionNames);
      namespace.houseNames = new HouseCollection();
      namespace.houseNames.reset(initHouseNames);
      namespace.senateNames = new SenateCollection();
      namespace.senateNames.reset(initSenateNames);
      this.countyRegionSelect = new WmsAreaSelectView({
        el: $('#areaSelectContainer')[0]
      });
      this.countyRegionSelect.render();
    };

    WMSRouter.prototype.updateViewsToNewYear = function(newYear) {
      var currRoute, newRoute, oldYear, y, _i, _len, _ref;
      currRoute = Backbone.history.fragment;
      oldYear = "";
      _ref = namespace.VALID_YEARS;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        y = _ref[_i];
        if (currRoute.indexOf(y + "/") !== -1) {
          oldYear = y;
          break;
        }
      }
      if (oldYear === "") {
        throw "Year invalid.";
        Backbone.history.navigate("");
      }
      newRoute = currRoute.replace(oldYear, newYear);
      Backbone.history.navigate("#/" + newRoute, {
        trigger: true
      });
    };

    WMSRouter.prototype.updateSelectedWug = function(wugId) {
      if (!wugId) {
        this.mapView.unselectWugFeatures();
      } else {
        this.mapView.selectWugFeature(wugId);
      }
    };

    WMSRouter.prototype.routes = {
      "": "default",
      ":year/wms": "wmsNetCountySupplies",
      ":year/wms/region/:regionLetter": "wmsRegion",
      ":year/wms/county/:countyId": "wmsCounty",
      ":year/wms/type/:typeId": "wmsType",
      ":year/wms/entity/:entityId": "wmsEntity",
      ":year/wms/project/:projectId": "wmsProjectDetail"
    };

    WMSRouter.prototype.before = {
      '': function(year) {
        if (this.currTableView != null) {
          this.currTableView = this.currTableView.unrender();
        }
        if (year != null) {
          if (_.contains(namespace.VALID_YEARS, year)) {
            namespace.currYear = year;
          } else {
            throw "Invalid Year.";
            return false;
          }
        }
      }
    };

    WMSRouter.prototype.after = {
      '': function(year) {
        if (year != null) {
          this.currTableView.render();
          this.currTableView.selectedWug.subscribe(this.updateSelectedWug);
          this.yearNavView.render();
          this.yearNavView.currentYear.subscribe(this.updateViewsToNewYear);
          return this.mapTopToolbarView.render();
        }
      }
    };

    WMSRouter.prototype["default"] = function() {
      Backbone.history.navigate("#/" + namespace.currYear + "/wms", {
        trigger: true
      });
    };

    WMSRouter.prototype.wmsNetCountySupplies = function(year) {
      if (this.currTableView != null) {
        this.currTableView = this.currTableView.unrender();
      }
      this.currTableView = new CountyNetSupplyCollectionView({
        el: this.tableContainer
      });
    };

    WMSRouter.prototype.wmsRegion = function(year, regionLetter) {
      this.currTableView = new RegionStrategyCollectionView({
        el: this.tableContainer,
        id: regionLetter,
        name: regionLetter
      });
    };

    WMSRouter.prototype.wmsCounty = function(year, countyId) {
      var countyName;
      countyName = namespace.countyNames.get(countyId).get('name');
      this.currTableView = new CountyStrategyCollectionView({
        el: this.tableContainer,
        id: countyId,
        name: countyName
      });
    };

    WMSRouter.prototype.wmsType = function(year, typeId) {
      var typeName;
      typeName = namespace.strategyTypes.get(typeId).get('name');
      this.currTableView = new StrategyTypeCollectionView({
        el: this.tableContainer,
        id: typeId,
        name: typeName
      });
    };

    WMSRouter.prototype.wmsEntity = function(year, entityId) {
      this.currTableView = new EntityStrategyCollectionView({
        el: this.tableContainer,
        id: entityId
      });
    };

    WMSRouter.prototype.wmsProjectDetail = function(year, projectId) {
      this.currTableView = new StrategyDetailCollectionView({
        el: this.tableContainer,
        id: projectId
      });
    };

    return WMSRouter;

  })(Backbone.Router);
});
