// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define([], function() {
  var Strategy;
  return Strategy = (function(_super) {

    __extends(Strategy, _super);

    function Strategy() {
      return Strategy.__super__.constructor.apply(this, arguments);
    }

    Strategy.prototype.urlRoot = "" + BASE_API_PATH + "api/strategy";

    Strategy.prototype.initialize = function() {
      return null;
    };

    return Strategy;

  })(Backbone.Model);
});
