// Generated by CoffeeScript 1.3.3

Ext.define('TNRIS.theme.InteractiveTheme', {
  /*
      Base class that provides a common interface for publishing events. 
      Subclasses are expected to to have a property "events" with all the events defined, 
      and, optionally, a property "listeners" with configured listeners defined.
  */

  mixins: {
    observable: 'Ext.util.Observable'
  },
  themeStore: null,
  mapComp: null,
  mainContainer: null,
  contentPanel: null,
  loadTheme: null,
  unloadTheme: null,
  constructor: function(config) {
    this.mixins.observable.constructor.call(this, config);
    return null;
  },
  unload: function() {
    var _this = this;
    this.themeStore.each(function(rec) {
      _this.mapComp.removeLayersFromMap(rec.data.Layers);
      return true;
    });
    this.unloadTheme();
    return null;
  },
  load: function() {
    this.loadTheme();
    return null;
  },
  updateYear: function(year) {
    return null;
  },
  showFeatureResult: function(features, clickedPoint, year) {
    return null;
  }
});
