// Generated by CoffeeScript 1.3.3

Ext.define('TNRIS.theme.StrategiesTheme', {
  extend: 'TNRIS.theme.InteractiveTheme',
  loadTheme: function() {
    console.log("load StrategiesTheme");
    return null;
  },
  unloadTheme: function() {
    console.log("unload StrategiesTheme");
    return null;
  }
});
