// Generated by CoffeeScript 1.3.3
﻿;

OpenLayers.Popup.Cosmo = OpenLayers.Class(OpenLayers.Popup.Framed, {
  contentDisplayClass: "olFramedCloudPopupContent",
  autoSize: true,
  panMapIfOutOfView: true,
  imageSize: new OpenLayers.Size(1276, 736),
  isAlphaImage: false,
  fixedRelativePosition: false,
  positionBlocks: {
    "tl": {
      'offset': new OpenLayers.Pixel(44, 0),
      'padding': new OpenLayers.Bounds(8, 40, 8, 9),
      'blocks': [
        {
          size: new OpenLayers.Size('auto', 'auto'),
          anchor: new OpenLayers.Bounds(0, 51, 22, 0),
          position: new OpenLayers.Pixel(0, 0)
        }, {
          size: new OpenLayers.Size(22, 'auto'),
          anchor: new OpenLayers.Bounds(null, 50, 0, 0),
          position: new OpenLayers.Pixel(-1238, 0)
        }, {
          size: new OpenLayers.Size('auto', 19),
          anchor: new OpenLayers.Bounds(0, 32, 22, null),
          position: new OpenLayers.Pixel(0, -631)
        }, {
          size: new OpenLayers.Size(22, 18),
          anchor: new OpenLayers.Bounds(null, 32, 0, null),
          position: new OpenLayers.Pixel(-1238, -632)
        }, {
          size: new OpenLayers.Size(81, 35),
          anchor: new OpenLayers.Bounds(null, 0, 0, null),
          position: new OpenLayers.Pixel(0, -688)
        }
      ]
    },
    "tr": {
      'offset': new OpenLayers.Pixel(-45, 0),
      'padding': new OpenLayers.Bounds(8, 40, 8, 9),
      'blocks': [
        {
          size: new OpenLayers.Size('auto', 'auto'),
          anchor: new OpenLayers.Bounds(0, 51, 22, 0),
          position: new OpenLayers.Pixel(0, 0)
        }, {
          size: new OpenLayers.Size(22, 'auto'),
          anchor: new OpenLayers.Bounds(null, 50, 0, 0),
          position: new OpenLayers.Pixel(-1238, 0)
        }, {
          size: new OpenLayers.Size('auto', 19),
          anchor: new OpenLayers.Bounds(0, 32, 22, null),
          position: new OpenLayers.Pixel(0, -631)
        }, {
          size: new OpenLayers.Size(22, 19),
          anchor: new OpenLayers.Bounds(null, 32, 0, null),
          position: new OpenLayers.Pixel(-1238, -631)
        }, {
          size: new OpenLayers.Size(81, 35),
          anchor: new OpenLayers.Bounds(0, 0, null, null),
          position: new OpenLayers.Pixel(-215, -687)
        }
      ]
    },
    "bl": {
      'offset': new OpenLayers.Pixel(45, 0),
      'padding': new OpenLayers.Bounds(8, 9, 8, 40),
      'blocks': [
        {
          size: new OpenLayers.Size('auto', 'auto'),
          anchor: new OpenLayers.Bounds(0, 21, 22, 32),
          position: new OpenLayers.Pixel(0, 0)
        }, {
          size: new OpenLayers.Size(22, 'auto'),
          anchor: new OpenLayers.Bounds(null, 21, 0, 32),
          position: new OpenLayers.Pixel(-1238, 0)
        }, {
          size: new OpenLayers.Size('auto', 21),
          anchor: new OpenLayers.Bounds(0, 0, 22, null),
          position: new OpenLayers.Pixel(0, -629)
        }, {
          size: new OpenLayers.Size(22, 21),
          anchor: new OpenLayers.Bounds(null, 0, 0, null),
          position: new OpenLayers.Pixel(-1238, -629)
        }, {
          size: new OpenLayers.Size(81, 33),
          anchor: new OpenLayers.Bounds(null, null, 0, 0),
          position: new OpenLayers.Pixel(-101, -674)
        }
      ]
    },
    "br": {
      'offset': new OpenLayers.Pixel(-44, 0),
      'padding': new OpenLayers.Bounds(8, 9, 8, 40),
      'blocks': [
        {
          size: new OpenLayers.Size('auto', 'auto'),
          anchor: new OpenLayers.Bounds(0, 21, 22, 32),
          position: new OpenLayers.Pixel(0, 0)
        }, {
          size: new OpenLayers.Size(22, 'auto'),
          anchor: new OpenLayers.Bounds(null, 21, 0, 32),
          position: new OpenLayers.Pixel(-1238, 0)
        }, {
          size: new OpenLayers.Size('auto', 21),
          anchor: new OpenLayers.Bounds(0, 0, 22, null),
          position: new OpenLayers.Pixel(0, -629)
        }, {
          size: new OpenLayers.Size(22, 21),
          anchor: new OpenLayers.Bounds(null, 0, 0, null),
          position: new OpenLayers.Pixel(-1238, -629)
        }, {
          size: new OpenLayers.Size(81, 33),
          anchor: new OpenLayers.Bounds(0, null, null, 0),
          position: new OpenLayers.Pixel(-311, -674)
        }
      ]
    }
  },
  initialize: function(id, lonlat, contentSize, contentHTML, anchor, closeBox, closeBoxCallback) {
    OpenLayers.Popup.FramedCloud.prototype.initialize.apply(this, arguments);
    this.imageSrc = '';
    this.contentDiv.className = this.contentDisplayClass;
  },
  CLASS_NAME: "OpenLayers.Popup.Cosmo"
});
