// Generated by CoffeeScript 1.3.3

Ext.define('ISWP.controller.Map', {
  extend: 'Ext.app.Controller',
  views: ['map.MapComponent'],
  stores: [],
  refs: [
    {
      ref: 'mapComponent',
      selector: 'mapcomponent'
    }
  ],
  init: function() {
    return this.control({
      'mapcomponent': {
        render: function(mapComp) {
          mapComp.map = mapComp.initializeMap(mapComp.el.dom);
          return null;
        }
      }
    });
  }
});
