---
- hosts: all
  sudo: yes
  vars_files:
    - variables.yml
  handlers:
    - include: handlers.yml

  tasks:
  - name: Add public key to vagrant's authorized_keys file
    authorized_key: user=vagrant key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    when: vagrant
    sudo: no

  - name: add vagrant sudoers file
    copy: src=vagrant_sudoers dest=/etc/sudoers.d/vagrant validate='visudo -cf %s' group=root owner=root mode=440
    when: vagrant

  - name: install python software properties package (for installing PPAs)
    apt: pkg=python-software-properties state=installed update_cache=yes cache_valid_time=86400

  - name: add nodejs ppa
    apt_repository: repo=ppa:chris-lea/node.js state=present

  - name: install node js
    apt: pkg=nodejs state=present

  - name: install monit
    apt: pkg=monit state=present

  - name: install upstart
    apt: pkg=monit state=present

  - name: install ruby
    apt: pkg=ruby state=present

  - name: install gem
    apt: pkg=rubygems state=present

  - name: install sass
    gem: name=sass state=present user_install=no

  - name: set up upstart config for water plan app
    template: src=water-plan-app-upstart-conf.j2 dest=/etc/init/{{ upstart_cmd }}.conf owner=root group=root mode=0644
    notify:
    - restart {{ upstart_cmd }}

  - include: varnish_tasks.yml

  - name: set up monit config for water plan app
    template: src=water-plan-app-monit-conf.j2 dest=/etc/monit/conf.d/{{ upstart_cmd }}.conf owner=root group=root mode=0644
    notify:
    - restart monit

  - name: create {{ water_plan_user }} account
    user: name={{ water_plan_user }}

  - name: create app dir
    file: path={{ app_dir }} state=directory recurse=yes owner={{ water_plan_user }} group={{ water_plan_user }}

  - name: build app dist
    local_action: command chdir=../application grunt build --force
    sudo: no

  - name: send app dist to server
    synchronize: src=../application/dist/ dest={{ app_dir }} archive=no recursive=yes rsync_path="sudo -u {{ water_plan_user }} rsync"
    notify:
    - restart {{ upstart_cmd }}
    - restart varnish

  - name: install npm packages
    npm: path={{ app_dir }}
    sudo_user: "{{ water_plan_user }}"
    notify:
    - restart {{ upstart_cmd }}
    - restart varnish
