---
  - name: install varnish
    apt: pkg=varnish

  - name: install monit
    apt: pkg=monit

  - name: set up monit config for varnish
    template: src=templates/varnish-monit-conf.j2 dest=/etc/monit/conf.d/varnish.conf owner=root group=root mode=0644
    notify:
    - restart monit

  - name: set up varnish config
    template: src=templates/varnish-conf.j2 dest=/etc/default/varnish owner=root group=root mode=0644
    notify:
    - restart varnish

  - name: set up varnish vcl
    template: src=templates/varnish-vcl.j2 dest=/etc/varnish/{{ upstart_cmd }}.vcl owner=root group=root mode=0644
    notify:
    - restart varnish
