// Generated by CoffeeScript 1.3.3
/*
The MapComponent holds the OpenLayers map.
*/

Ext.define('ISWP.view.map.MapComponent', {
  extend: 'Ext.Component',
  alias: 'widget.mapcomponent',
  map: null,
  vectorLayer: null,
  bingApiKey: 'Aq7OR-oOdjT5kHB1zKYF7O55CZsiZHai_UnX3blamGr2l94e1b9YyAWOrz9NcX9N',
  featureControl: null,
  selectFeatureControlId: null,
  store: '',
  origCenter: new OpenLayers.LonLat(-99.294317, 31.348335).transform(new OpenLayers.Projection("EPSG:4326"), new OpenLayers.Projection("EPSG:3857")),
  origZoom: 6,
  handleMapEvent: function(evt) {
    return null;
  },
  initializeMap: function() {
    var bing_aerial, bing_hybrid, bing_road, esri_gray, mapquest_aerial, mapquest_open;
    mapquest_open = new OpenLayers.Layer.XYZ("MapQuest Open Street", ["http://otile1.mqcdn.com/tiles/1.0.0/osm/${z}/${x}/${y}.png", "http://otile2.mqcdn.com/tiles/1.0.0/osm/${z}/${x}/${y}.png", "http://otile3.mqcdn.com/tiles/1.0.0/osm/${z}/${x}/${y}.png", "http://otile4.mqcdn.com/tiles/1.0.0/osm/${z}/${x}/${y}.png"], {
      attribution: "Tiles courtesy <a href='http://www.mapquest.com/' target='_blank'>MapQuest</a>",
      transitionEffect: "resize"
    });
    mapquest_aerial = new OpenLayers.Layer.XYZ("MapQuest Open Aerial", ["http://oatile1.mqcdn.com/tiles/1.0.0/sat/${z}/${x}/${y}.png", "http://oatile2.mqcdn.com/tiles/1.0.0/sat/${z}/${x}/${y}.png", "http://oatile3.mqcdn.com/tiles/1.0.0/sat/${z}/${x}/${y}.png", "http://oatile4.mqcdn.com/tiles/1.0.0/sat/${z}/${x}/${y}.png"], {
      attribution: "Tiles courtesy <a href='http://www.mapquest.com/' target='_blank'>MapQuest</a>",
      transitionEffect: "resize"
    });
    bing_road = new OpenLayers.Layer.Bing({
      name: "Bing Road",
      key: this.bingApiKey,
      type: "Road",
      transitionEffect: "resize"
    });
    bing_hybrid = new OpenLayers.Layer.Bing({
      name: "Bing Hybrid",
      key: this.bingApiKey,
      type: "AerialWithLabels",
      transitionEffect: "resize"
    });
    bing_aerial = new OpenLayers.Layer.Bing({
      name: "Bing Aerial",
      key: this.bingApiKey,
      type: "Aerial",
      transitionEffect: "resize"
    });
    esri_gray = new OpenLayers.Layer.XYZ('ESRI Gray', ['http://services.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/${z}/${y}/${x}'], {
      attribution: "Tiles courtesy <a href='http://www.esri.com' target='_blank'>esri</a>"
    });
    this.map = new OpenLayers.Map({
      div: this.id,
      projection: new OpenLayers.Projection("EPSG:3857"),
      displayProjection: new OpenLayers.Projection("EPSG:4326"),
      layers: [esri_gray, bing_road, mapquest_open, mapquest_aerial, bing_hybrid, bing_aerial],
      center: this.origCenter,
      zoom: this.origZoom,
      eventListeners: {
        moveend: this.handleMapEvent,
        click: this.handleMapEvent
      }
    });
    this.map.addControl(new OpenLayers.Control.LayerSwitcher());
    return this.map;
  },
  resetExtent: function() {
    return this.map.setCenter(this.origCenter, this.origZoom);
  },
  removePopupsFromMap: function() {
    var p, _i, _len, _ref, _results;
    _ref = this.map.popups;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      p = _ref[_i];
      _results.push(this.map.removePopup(p));
    }
    return _results;
  },
  removeLayersFromMap: function(layers) {
    var layer, map_lyr, _i, _j, _len, _len1, _ref;
    for (_i = 0, _len = layers.length; _i < _len; _i++) {
      layer = layers[_i];
      _ref = this.map.getLayersByName(layer.Name);
      for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
        map_lyr = _ref[_j];
        this.map.removeLayer(map_lyr);
        map_lyr.destroy();
      }
    }
    return null;
  },
  addLayersToMap: function(layers) {
    this.map.addLayers(layers);
    return null;
  },
  clearVectorLayer: function() {
    var ctl;
    if (this.selectFeatureControlId != null) {
      ctl = this.map.getControl(this.selectFeatureControlId);
      ctl.destroy();
      this.map.removeControl(ctl);
      this.selectFeatureControlId = null;
    }
    if (this.vectorLayer != null) {
      this.vectorLayer.destroy();
    }
    return null;
  },
  removeFeatureControl: function() {
    if (this.featureControl != null) {
      this.featureControl.destroy();
      return this.map.removeControl(this.featureControl);
    }
  },
  setupFeatureControl: function(layers) {
    var info,
      _this = this;
    this.removeFeatureControl();
    info = new OpenLayers.Control.GetFeature({
      layers: layers,
      serviceUrl: 'Feature/Reservoir/Proposed',
      title: 'Identify Features by Clicking',
      queryVisible: true,
      maxFeatures: 1,
      eventListeners: {
        nofeaturefound: function(evt) {
          _this.fireEvent("nofeaturefound", _this, evt);
          return null;
        },
        getfeature: function(evt) {
          _this.fireEvent("getfeature", _this, evt);
          return null;
        }
      }
    });
    this.map.addControl(info);
    info.activate();
    return this.featureControl = info;
  }
});
