// Generated by CoffeeScript 1.3.3
/*
The ThemeYearMapPanel is a Panel that holds a MapComponent and
 the toolbars for controlling the current data view of the application.
*/

Ext.define('ISWP.view.map.ThemeYearMapPanel', {
  extend: 'Ext.panel.Panel',
  alias: 'widget.themeyearmappanel',
  layout: 'fit',
  items: [
    {
      xtype: 'mapcomponent',
      id: 'mapComponent'
    }
  ],
  dockedItems: [
    {
      xtype: 'toolbar',
      dock: 'bottom',
      id: 'yearButtonBar',
      items: [
        'Planning Decade: ', {
          xtype: 'button',
          text: '2010',
          year: 2010,
          pressed: true,
          allowDepress: false,
          toggleGroup: 'yearButtons'
        }, {
          xtype: 'button',
          text: '2020',
          year: 2020,
          allowDepress: false,
          toggleGroup: 'yearButtons'
        }, {
          xtype: 'button',
          text: '2030',
          year: 2030,
          allowDepress: false,
          toggleGroup: 'yearButtons'
        }, {
          xtype: 'button',
          text: '2040',
          year: 2040,
          allowDepress: false,
          toggleGroup: 'yearButtons'
        }, {
          xtype: 'button',
          text: '2050',
          year: 2050,
          allowDepress: false,
          toggleGroup: 'yearButtons'
        }, {
          xtype: 'button',
          text: '2060',
          year: 2060,
          allowDepress: false,
          toggleGroup: 'yearButtons'
        }, '-', '->', {
          xtype: 'button',
          text: 'Zoom to Texas',
          id: 'resetExtentButton'
        }, '-', {
          xtype: 'combobox',
          hideLabel: false,
          fieldLabel: 'Zoom to Location',
          emptyText: 'Enter a Location Name',
          width: 350
        }
      ]
    }, {
      xtype: 'toolbar',
      dock: 'left',
      id: 'themeButtonBar',
      items: [
        {
          xtype: 'button',
          text: 'Existing Supply',
          theme: 'water-use',
          allowDepress: false,
          toggleGroup: 'themeButtons'
        }, {
          xtype: 'button',
          text: 'Recommended Reservoirs',
          theme: 'proposed-reservoirs',
          pressed: true,
          allowDepress: false,
          toggleGroup: 'themeButtons'
        }
      ]
    }
  ],
  getSelectedTheme: function() {
    var selectedTheme;
    selectedTheme = null;
    this.dockedItems.getByKey('themeButtonBar').items.each(function(item) {
      if (item.xtype === 'button' && item.pressed) {
        selectedTheme = item.theme;
        return false;
      }
    });
    return selectedTheme;
  },
  getSelectedYear: function() {
    var selectedYear;
    selectedYear = null;
    this.dockedItems.getByKey('yearButtonBar').items.each(function(item) {
      if (item.xtype === 'button' && item.pressed) {
        selectedYear = item.year;
        return false;
      }
    });
    return selectedYear;
  }
});
