// Generated by CoffeeScript 1.3.3
/*
The ThemeYearMapPanel is a Panel that holds a MapComponent and
 the toolbars for controlling the current data view of the application.
*/

Ext.define('ISWP.view.map.ThemeYearMapPanel', {
  extend: 'Ext.panel.Panel',
  alias: 'widget.themeyearmappanel',
  layout: 'fit',
  items: [
    {
      xtype: 'mapcomponent',
      id: 'mapComponent'
    }
  ],
  dockedItems: [
    {
      xtype: 'toolbar',
      dock: 'bottom',
      id: 'yearButtonBar',
      items: [
        'Planning Year: ', {
          xtype: 'button',
          text: '2012',
          year: 2012,
          pressed: true,
          toggleGroup: 'yearButtons'
        }, {
          xtype: 'button',
          text: '2020',
          year: 2020,
          toggleGroup: 'yearButtons'
        }, {
          xtype: 'button',
          text: '2030',
          year: 2030,
          toggleGroup: 'yearButtons'
        }, {
          xtype: 'button',
          text: '2040',
          year: 2040,
          toggleGroup: 'yearButtons'
        }, {
          xtype: 'button',
          text: '2050',
          year: 2050,
          toggleGroup: 'yearButtons'
        }, {
          xtype: 'button',
          text: '2060',
          year: 2060,
          toggleGroup: 'yearButtons'
        }, '-', '->', {
          xtype: 'button',
          text: 'Zoom to Texas',
          id: 'resetExtentButton'
        }, {
          xtype: 'combobox',
          hideLabel: true,
          emptyText: 'Enter a Location Name',
          width: 200
        }
      ]
    }, {
      xtype: 'toolbar',
      dock: 'left',
      id: 'themeButtonBar',
      items: [
        {
          xtype: 'button',
          text: 'Water Use',
          theme: 'water-use',
          toggleGroup: 'themeButtons'
        }, {
          xtype: 'button',
          text: 'Proposed Reservoirs',
          theme: 'proposed-reservoirs',
          pressed: true,
          toggleGroup: 'themeButtons'
        }, {
          xtype: 'button',
          text: 'Theme 3',
          theme: 'theme-3',
          toggleGroup: 'themeButtons'
        }, {
          xtype: 'button',
          text: 'Theme 4',
          theme: 'theme-4',
          toggleGroup: 'themeButtons'
        }, {
          xtype: 'button',
          text: 'Theme 5',
          theme: 'theme-5',
          toggleGroup: 'themeButtons'
        }
      ]
    }
  ],
  getSelectedTheme: function() {
    var selectedTheme;
    selectedTheme = null;
    this.dockedItems.getByKey('themeButtonBar').items.each(function(item) {
      if (item.xtype === 'button' && item.pressed) {
        selectedTheme = item.theme;
        return false;
      }
    });
    return selectedTheme;
  },
  getSelectedYear: function() {
    var selectedYear;
    selectedYear = null;
    this.dockedItems.getByKey('yearButtonBar').items.each(function(item) {
      if (item.xtype === 'button' && item.pressed) {
        selectedYear = item.year;
        return false;
      }
    });
    return selectedYear;
  }
});
