// Generated by CoffeeScript 1.3.3

Ext.define('ISWP.model.ReservoirSupplyData', {
  extend: 'Ext.data.Model',
  fields: ['Irrigation', 'Livestock', 'Manufacturing', 'Mining', 'Municipal', 'SteamElectricPower']
});
