// Generated by CoffeeScript 1.3.3

Ext.define('ISWP.store.WaterUseData', {
  extend: 'Ext.data.Store',
  model: 'ISWP.model.WaterUseData',
  storeId: 'waterUseDataStore',
  data: [
    {
      Name: 'Agriculture',
      Value: 500
    }, {
      Name: 'Municipal',
      Value: 300
    }, {
      Name: 'Power',
      Value: 150
    }, {
      Name: 'Livestock',
      Value: 80
    }, {
      Name: 'Industrial',
      Value: 200
    }
  ]
});
