// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define([], function() {
  var HouseNamesCollection;
  return HouseNamesCollection = (function(_super) {

    __extends(HouseNamesCollection, _super);

    function HouseNamesCollection() {
      return HouseNamesCollection.__super__.constructor.apply(this, arguments);
    }

    HouseNamesCollection.prototype.url = "" + BASE_PATH + "api/boundary/districts/house/names";

    return HouseNamesCollection;

  })(Backbone.Collection);
});
