// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define([], function() {
  var RegionNamesCollection;
  return RegionNamesCollection = (function(_super) {

    __extends(RegionNamesCollection, _super);

    function RegionNamesCollection() {
      return RegionNamesCollection.__super__.constructor.apply(this, arguments);
    }

    RegionNamesCollection.prototype.url = "" + BASE_API_PATH + "api/boundary/regions/names";

    RegionNamesCollection.prototype.model = Backbone.Model.extend({
      idAttribute: 'letter'
    });

    return RegionNamesCollection;

  })(Backbone.Collection);
});
