// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['models/Strategy'], function(Strategy) {
  var StrategyCollection;
  return StrategyCollection = (function(_super) {

    __extends(StrategyCollection, _super);

    function StrategyCollection() {
      return StrategyCollection.__super__.constructor.apply(this, arguments);
    }

    StrategyCollection.prototype.model = Strategy;

    StrategyCollection.prototype.url = "" + BASE_API_PATH + "api/strategy/all";

    return StrategyCollection;

  })(Backbone.Collection);
});
