// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define([], function() {
  var WugFeatureCollection;
  return WugFeatureCollection = (function(_super) {

    __extends(WugFeatureCollection, _super);

    function WugFeatureCollection() {
      return WugFeatureCollection.__super__.constructor.apply(this, arguments);
    }

    return WugFeatureCollection;

  })(Backbone.Collection);
});
