// Generated by CoffeeScript 1.3.3

Ext.define('ISWP.store.County', {
  extend: 'Ext.data.Store',
  model: 'ISWP.model.Place',
  storeId: 'countyStore',
  autoLoad: true,
  proxy: {
    type: 'ajax',
    url: 'api/place/all',
    reader: {
      type: 'json'
    }
  }
});
