// Generated by CoffeeScript 1.3.3

Ext.define('ISWP.store.PlaceFeature', {
  extend: 'Ext.data.Store',
  fields: ['SqlId', 'Name', 'WKTGeog'],
  storeId: 'placeFeatureStore',
  autoLoad: false,
  proxy: {
    type: 'parameterproxy',
    url: 'api/place/feature/{placeId}',
    reader: {
      type: 'json'
    }
  }
});
