// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/MapView', 'views/ThemeNavView', 'views/YearNavView', 'views/BreadcrumbView', 'views/CountyNetSupplyCollectionView', 'views/StrategyCollectionView', 'scripts/text!templates/appContainer.html'], function(MapView, ThemeNavView, YearNavView, BreadcrumbView, CountyNetSupplyCollectionView, StrategyCollectionView, tpl) {
  var AppView;
  return AppView = (function(_super) {

    __extends(AppView, _super);

    function AppView() {
      return AppView.__super__.constructor.apply(this, arguments);
    }

    AppView.prototype.startingYear = "2010";

    AppView.prototype.initialize = function() {
      _.bindAll(this, 'render', 'unrender', 'updateViewsToNewYear');
      this.template = _.template(tpl);
    };

    AppView.prototype.render = function() {
      this.$el.html(this.template());
      this.mapView = new MapView('mapContainer');
      this.mapView.render();
      this.themeNavView = new ThemeNavView({
        el: $('#themeNavContainer')[0]
      });
      this.themeNavView.render();
      this.yearNavView = new YearNavView({
        startingYear: this.startingYear,
        el: $('#yearNavContainer')[0]
      });
      this.yearNavView.render();
      this.yearNavView.currentYear.subscribe(this.updateViewsToNewYear);
      this.breadcrumbList = new BreadcrumbView({
        el: $('#breadcrumbContainer')[0]
      });
      this.breadcrumbList.render();
      this.currTableView = new CountyNetSupplyCollectionView({
        startingYear: this.startingYear,
        el: $('#tableContainer')[0]
      });
      this.currTableView.render();
      return this;
    };

    AppView.prototype.unrender = function() {
      this.el.remove();
      return null;
    };

    AppView.prototype.updateViewsToNewYear = function(newYear) {
      console.log("changed year to " + newYear);
      this.currTableView.changeToYear(newYear);
    };

    return AppView;

  })(Backbone.View);
});
