// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['scripts/text!templates/breadcrumbList.html'], function(tpl) {
  var BreadcrumbViewModel;
  return BreadcrumbViewModel = (function(_super) {

    __extends(BreadcrumbViewModel, _super);

    function BreadcrumbViewModel() {
      return BreadcrumbViewModel.__super__.constructor.apply(this, arguments);
    }

    BreadcrumbViewModel.prototype.template = _.template(tpl);

    BreadcrumbViewModel.prototype.render = function() {
      this.$el.empty();
      this.$el.html(this.template());
      ko.applyBindings(this, this.el);
      return this;
    };

    BreadcrumbViewModel.prototype.unrender = function() {
      this.$el.remove();
      return null;
    };

    BreadcrumbViewModel.prototype.initialize = function() {
      this.$el = $(this.el);
      _.bindAll(this, 'render', 'unrender');
      return null;
    };

    return BreadcrumbViewModel;

  })(Backbone.View);
});
