// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['namespace', 'scripts/text!templates/countyNetSupplyRow.html'], function(namespace, tpl) {
  var CountyNetSupplyView;
  return CountyNetSupplyView = (function(_super) {

    __extends(CountyNetSupplyView, _super);

    function CountyNetSupplyView() {
      return CountyNetSupplyView.__super__.constructor.apply(this, arguments);
    }

    CountyNetSupplyView.prototype.tagName = 'tr';

    CountyNetSupplyView.prototype.initialize = function() {
      _.bindAll(this, 'render', 'unrender');
      this.template = _.template(tpl);
      return null;
    };

    CountyNetSupplyView.prototype.render = function() {
      this.$el.html(this.template({
        m: this.model.toJSON(),
        currYear: namespace.currYear
      }));
      return this;
    };

    CountyNetSupplyView.prototype.unrender = function() {
      this.$el.remove();
      return null;
    };

    return CountyNetSupplyView;

  })(Backbone.View);
});
