// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/BaseTableCollectionView', 'views/CountyNetSupplyView', 'collections/CountyNetSupplyCollection', 'scripts/text!templates/countyNetSupplyTable.html'], function(BaseTableCollectionView, CountyNetSupplyView, CountyNetSupplyCollection, tpl) {
  var CountyNetSupplyCollectionView;
  return CountyNetSupplyCollectionView = (function(_super) {

    __extends(CountyNetSupplyCollectionView, _super);

    function CountyNetSupplyCollectionView() {
      return CountyNetSupplyCollectionView.__super__.constructor.apply(this, arguments);
    }

    CountyNetSupplyCollectionView.prototype.initialize = function(options) {
      _.bindAll(this, 'selectCounty', 'selectRegion');
      CountyNetSupplyCollectionView.__super__.initialize.call(this, options.currYear, CountyNetSupplyView, CountyNetSupplyCollection, tpl);
      this.selectedCounty = ko.observable();
      this.selectedRegion = ko.observable();
      return null;
    };

    CountyNetSupplyCollectionView.prototype.selectCounty = function(data, event) {
      var $target, countyId, countyName;
      $target = $(event.target);
      countyId = $target.data('value');
      countyName = $target.data('name');
      this.selectedCounty({
        id: countyId,
        name: countyName
      });
      return null;
    };

    CountyNetSupplyCollectionView.prototype.selectRegion = function(data, event) {
      var $target, regionLetter;
      $target = $(event.target);
      regionLetter = $target.data('value');
      this.selectedRegion({
        id: regionLetter,
        name: regionLetter
      });
      return null;
    };

    return CountyNetSupplyCollectionView;

  })(BaseTableCollectionView);
});
