// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['scripts/text!templates/entityStrategyRow.html'], function(tpl) {
  var EntityStrategyView;
  return EntityStrategyView = (function(_super) {

    __extends(EntityStrategyView, _super);

    function EntityStrategyView() {
      return EntityStrategyView.__super__.constructor.apply(this, arguments);
    }

    EntityStrategyView.prototype.tagName = 'tr';

    EntityStrategyView.prototype.initialize = function(options) {
      EntityStrategyView.__super__.initialize.call(this, options);
      this.currYear = options.currYear;
      _.bindAll(this, 'render', 'unrender');
      this.template = _.template(tpl);
      return null;
    };

    EntityStrategyView.prototype.render = function() {
      this.$el.html(this.template({
        m: this.model.toJSON(),
        currYear: this.currYear
      }));
      return this;
    };

    EntityStrategyView.prototype.unrender = function() {
      this.$el.remove();
      return null;
    };

    return EntityStrategyView;

  })(Backbone.View);
});
