// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['namespace', 'views/BaseStrategyView', 'scripts/text!templates/entityStrategyRow.html'], function(namespace, BaseStrategyView, tpl) {
  var EntityStrategyView;
  return EntityStrategyView = (function(_super) {

    __extends(EntityStrategyView, _super);

    function EntityStrategyView() {
      return EntityStrategyView.__super__.constructor.apply(this, arguments);
    }

    EntityStrategyView.prototype.template = tpl;

    return EntityStrategyView;

  })(BaseStrategyView);
});
