// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['namespace', 'collections/StrategyTypeCollection', 'scripts/text!templates/strategyTypeListItem.html', 'scripts/text!templates/mapTopToolbar.html'], function(namespace, StrategyTypeCollection, strategyTypeListItemTpl, tpl) {
  var MapTopToolbarView;
  return MapTopToolbarView = (function(_super) {

    __extends(MapTopToolbarView, _super);

    function MapTopToolbarView() {
      return MapTopToolbarView.__super__.constructor.apply(this, arguments);
    }

    MapTopToolbarView.prototype.template = _.template(tpl);

    MapTopToolbarView.prototype.mapView = null;

    MapTopToolbarView.prototype.initialize = function(options) {
      _.bindAll(this, 'render', 'unrender', 'renderStrategyTypeList', 'zoomToTexas');
      this.mapView = options.mapView;
      return null;
    };

    MapTopToolbarView.prototype.render = function() {
      var $btn;
      this.$el.empty();
      this.$el.html(this.template({
        currYear: namespace.currYear
      }));
      ko.applyBindings(this, this.el);
      if ($("#mapContainer").is(":hidden")) {
        $btn = this.$('#toggleMapBtn');
        $btn.addClass('on');
        this.toggleMap(null, null, $btn);
      }
      this.renderStrategyTypeList();
      return this;
    };

    MapTopToolbarView.prototype.renderStrategyTypeList = function() {
      var stratTypeLiTemplate, typeCollection,
        _this = this;
      stratTypeLiTemplate = _.template(strategyTypeListItemTpl);
      typeCollection = new StrategyTypeCollection();
      typeCollection.fetch({
        success: function(collection) {
          var res, strategyType, _i, _len, _ref;
          _ref = collection.models;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            strategyType = _ref[_i];
            res = _this.$('#strategyTypeList').append(stratTypeLiTemplate({
              m: strategyType.toJSON(),
              currYear: namespace.currYear
            }));
          }
        }
      });
    };

    MapTopToolbarView.prototype.unrender = function() {
      this.$el.remove();
      return null;
    };

    MapTopToolbarView.prototype.zoomToTexas = function() {
      this.mapView.resetExtent();
    };

    MapTopToolbarView.prototype.toggleMap = function(data, event, $el) {
      var $target;
      if ($el != null) {
        $target = $el;
      } else {
        $target = $(event.target);
      }
      if ($target.hasClass('off')) {
        $target.html('Hide Map');
        $('#mapContainer').slideDown();
        $('.map-stuff').show();
        $target.removeClass('off');
      } else {
        $target.addClass('off');
        $('#mapContainer').slideUp();
        $('.map-stuff').hide();
        $target.html('Show Map');
      }
    };

    return MapTopToolbarView;

  })(Backbone.View);
});
