// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/BaseTableCollectionView', 'views/StrategyView', 'collections/StrategyCollection', 'scripts/text!templates/strategyTable.html'], function(BaseTableCollectionView, StrategyView, StrategyCollection, tpl) {
  var StrategyCollectionView;
  return StrategyCollectionView = (function(_super) {

    __extends(StrategyCollectionView, _super);

    function StrategyCollectionView() {
      return StrategyCollectionView.__super__.constructor.apply(this, arguments);
    }

    StrategyCollectionView.prototype.initialize = function() {
      StrategyCollectionView.__super__.initialize.call(this, StrategyView, StrategyCollection, tpl);
      return null;
    };

    return StrategyCollectionView;

  })(BaseTableCollectionView);
});
