// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['namespace', 'scripts/text!templates/strategyDetailRow.html'], function(namespace, tpl) {
  var StrategyDetailView;
  return StrategyDetailView = (function(_super) {

    __extends(StrategyDetailView, _super);

    function StrategyDetailView() {
      return StrategyDetailView.__super__.constructor.apply(this, arguments);
    }

    StrategyDetailView.prototype.tagName = 'tr';

    StrategyDetailView.prototype.initialize = function(options) {
      StrategyDetailView.__super__.initialize.call(this, options);
      _.bindAll(this, 'render', 'unrender');
      this.template = _.template(tpl);
      return null;
    };

    StrategyDetailView.prototype.render = function() {
      this.$el.html(this.template({
        m: this.model.toJSON(),
        currYear: namespace.currYear
      }));
      return this;
    };

    StrategyDetailView.prototype.unrender = function() {
      this.$el.remove();
      return null;
    };

    return StrategyDetailView;

  })(Backbone.View);
});
