// Generated by CoffeeScript 1.3.3
﻿;

Ext.Loader.setConfig({
  enabled: true,
  disableCaching: false
});

Ext.create('Ext.app.Application', {
  name: 'ISWP',
  autoCreateViewport: true,
  appFolder: 'Scripts/Compiled/app',
  controllers: ['Map'],
  launch: function() {
    return null;
  }
});
